// <auto-generated />
namespace IhorsSlaves.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ShortPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShortPost));
        
        string IMigrationMetadata.Id
        {
            get { return "201310310953394_ShortPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
